// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7EtqclxEHby4eA-uTKANCKyXpmXdbj4',
    appId: '1:1089028282766:web:b5f22f9e95642df079ecdf',
    messagingSenderId: '1089028282766',
    projectId: 'accountapp-8a1a9',
    authDomain: 'accountapp-8a1a9.firebaseapp.com',
    storageBucket: 'accountapp-8a1a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctRhL9Ky8k4kKS8IoDUb1s7HShKhNXLc',
    appId: '1:1089028282766:android:793e1bde8d11913c79ecdf',
    messagingSenderId: '1089028282766',
    projectId: 'accountapp-8a1a9',
    storageBucket: 'accountapp-8a1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJ27uYL5OWwOOMTLyKrcGCR7r_b43PxQ',
    appId: '1:1089028282766:ios:ba3d4ccf91f0d94979ecdf',
    messagingSenderId: '1089028282766',
    projectId: 'accountapp-8a1a9',
    storageBucket: 'accountapp-8a1a9.appspot.com',
    iosClientId: '1089028282766-gifg755lmtm9v3teijhgmlkvmret4kh1.apps.googleusercontent.com',
    iosBundleId: 'com.accountantshellcode.accountantApp',
  );
}
